### ISSUE TITLE
Use PDO if possible

### ISSUE THREAD

**Issue by steckerhalter** [J-8/ShoppingList_backend#38] opened 2015-09-15 05:41 UTC
To eliminate the need for two database adapters I think http://php.net/manual/en/book.pdo.php should provide the necessary abstractions...

**Comment by jklmnn** [comment] 2015-09-18 06:50
@beli3ver Why did we fork that from master? I'd recommend to fork new functionalities/APIs from experimental (which is going to be the next version I think). The problem is, that all improvements we do on master, we have to do also on experimental.

**Comment by ghost** [comment] 2015-09-20 17:08
ok, sorry my mistake :-1:

**Comment by jklmnn** [comment] 2015-09-24 14:19
I have looked through pdo and I will create a db connector that will replace the current connectors.
The config will be unchanged so the replace should work without breaking things.

**Comment by jklmnn** [comment] 2015-09-25 11:41
I have completed my db connector with pdo.
You can test it in the devel branch.
Currently the table for the database is created within api.php and exceptions for creating a table that already exist are ignored. The table creation should happen in INSTALL.php. I will correct this as soon as #50 has been merged/closed to prevent merging issues.
@J-8 you may test this with your app please. I had some issues with saveMultiple but I those might be encoding related (I tested with curl).

**Comment by the0ne** [comment] 2016-06-03 11:20
the pdo db connector works great!

**Closed as completed** 2016-06-03 11:39 UTC
Labels: enhancement
